{% set name = "napari-plugin-search" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-plugin-search-{{ version }}.tar.gz
  sha256: 6dcc0793d072777c8d0cfebff89281252e57e13f8e13a8e0458a9ba7d86a06a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_plugin_search
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-plugin-search
  summary: Find napari plugins
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
